import { useEffect, useMemo, useState } from 'react';
import { NavLink, Route, Routes, useLocation } from 'react-router-dom';
import * as Icons from 'lucide-react';
import { getContent, searchContent } from './api/contentApi';

const navigation = [
  ['/', 'Home'], ['/news', 'News'], ['/blogs', 'Blogs'], ['/activities', 'Get Involved'], ['/topics', 'SDG Topics'], ['/search', 'Search']
];
const iconFor = (name, props) => { const Icon = Icons[name] || Icons.Circle; return <Icon {...props} />; };

function Brand() { return <NavLink to="/" className="brand" aria-label="Sustainable XJTLU home"><span className="brand-mark"><Icons.Sprout size={27}/></span><span>Sustainable<br/><b>XJTLU</b></span></NavLink>; }
function Layout({children}) { const location = useLocation(); return <><header><Brand/><nav>{navigation.slice(0, 5).map(([to, label]) => <NavLink key={to} to={to} className={({isActive}) => isActive ? 'active' : ''}>{label}</NavLink>)}</nav><div className="header-actions"><NavLink to="/search" className={location.pathname === '/search' ? 'search-active' : ''} aria-label="Search"><Icons.Search size={23}/></NavLink><button className="language">EN <Icons.ChevronDown size={15}/></button></div></header><main>{children}</main><footer><Brand/><p>Creating a more sustainable university, together.</p><span>© 2026 Xi'an Jiaotong-Liverpool University</span></footer></> }
function useContent() { const [data, setData] = useState(); useEffect(() => { getContent().then(setData); }, []); return data; }
function Loader(){ return <div className="loading">Loading sustainable stories…</div> }
function ArrowLink({to, children}) { return <NavLink className="arrow-link" to={to}>{children}<Icons.ArrowUpRight size={18}/></NavLink> }

function CampusIllustration(){ return <div className="campus-art" aria-hidden="true"><div className="art-sun"></div><div className="art-cloud cloud-a"></div><div className="art-cloud cloud-b"></div><div className="art-building"><i/><i/><i/><i/><i/><i/></div><div className="art-trees"><span/><span/><span/><span/><span/></div><div className="art-ground"/></div> }
function Hero({data}) { return <section className="hero"><div className="hero-copy"><p className="eyebrow">University sustainability</p><h1>Sustainable <em>XJTLU</em></h1><div className="rule"/><p className="lead">{data.site.intro}</p><ArrowLink to="/activities"><span className="button-link">Get involved</span></ArrowLink></div><div className="hero-art"><h2>{data.site.tagline}</h2><CampusIllustration/></div></section> }
function TopicCards({topics, compact=false}) { return <div className={compact ? 'topic-grid compact' : 'topic-grid'}>{topics.map(topic => <NavLink className="topic-card" key={topic.id} to={`/topics?topic=${topic.id}`}><span className={`topic-icon ${topic.tone}`}>{iconFor(topic.icon, {size: compact ? 25 : 32, strokeWidth:1.7})}</span><b>{topic.title}</b>{!compact && <p>{topic.description}</p>}</NavLink>)}</div> }
function PortalCard({icon, title, description, link, tint}) { return <section className={`portal-card ${tint}`}><span className="portal-icon">{icon}</span><h3>{title}</h3><p>{description}</p><ArrowLink to={link}>Explore {title}</ArrowLink></section> }
function Home(){ const data = useContent(); if(!data) return <Loader/>; return <><Hero data={data}/><section className="section topic-section"><div className="section-heading"><h2>Explore by SDG Topics</h2><ArrowLink to="/topics">View all topics</ArrowLink></div><TopicCards topics={data.topics} compact/></section><section className="section portals"><PortalCard icon={<Icons.Newspaper/>} title="News" description="Latest updates and announcements on sustainability at XJTLU." link="/news" tint="news"/><PortalCard icon={<Icons.PenLine/>} title="Blogs" description="Insights and stories from our community on sustainable living and innovation." link="/blogs" tint="blogs"/><PortalCard icon={<Icons.HandHeart/>} title="Get Involved" description="Join activities, projects and initiatives to make a real impact." link="/activities" tint="involved"/></section><section className="section search-banner"><span className="search-bubble"><Icons.Search/></span><div><h2>Search our content</h2><p>Find news, blogs, activities and more related to sustainability at XJTLU.</p></div><ArrowLink to="/search"><span className="outlined-button">Search</span></ArrowLink></section></> }
function Listing({type, title, intro}) { const data=useContent(); if(!data) return <Loader/>; const collection=data[type]; return <section className="page"><div className="page-intro"><p className="eyebrow">Sustainable XJTLU</p><h1>{title}</h1><p>{intro}</p></div><div className="story-grid">{collection.map((item, index)=><article className={`story-card ${item.accent||''}`} key={item.id}><div className="story-visual"><span>{type === 'news' ? <Icons.Newspaper/> : <Icons.PenLine/>}</span><small>0{index+1}</small></div><div className="story-content"><div className="meta">{item.type || item.author} <i/> {item.date || item.readTime}</div><h2>{item.title}</h2><p>{item.excerpt}</p><button className="text-button">Read story <Icons.ArrowRight size={17}/></button></div></article>)}</div></section> }
function Activities(){const data=useContent();if(!data)return <Loader/>;return <section className="page"><div className="page-intro"><p className="eyebrow">Make a difference</p><h1>Get involved</h1><p>Find a way to turn your interest in sustainability into positive action.</p></div><div className="activity-list">{data.activities.map(activity=><article className="activity" key={activity.id}><div className="date-block"><b>{activity.date.split(' ')[0]}</b><span>{activity.date.split(' ')[1]}</span></div><div><span className="pill">{activity.category}</span><h2>{activity.title}</h2><p>{activity.summary}</p><div className="activity-detail"><span><Icons.Clock3/> {activity.time}</span><span><Icons.MapPin/> {activity.place}</span></div></div><button className="round-button" aria-label={`Learn more about ${activity.title}`}><Icons.ArrowUpRight/></button></article>)}</div></section>}
function Topics(){const data=useContent();if(!data)return <Loader/>;return <section className="page"><div className="page-intro"><p className="eyebrow">Shared challenges, shared progress</p><h1>SDG Topics</h1><p>Explore the areas where the XJTLU community is focusing energy, ideas and action.</p></div><TopicCards topics={data.topics}/></section>}
function Search(){const [query,setQuery]=useState(''); const [results,setResults]=useState([]); useEffect(()=>{searchContent(query).then(setResults)},[query]);return <section className="page search-page"><div className="page-intro"><p className="eyebrow">Discover more</p><h1>Search</h1><p>Search sustainability news, ideas, activities and topics.</p></div><label className="search-input"><Icons.Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="What are you looking for?" autoFocus/><button onClick={()=>setQuery('')}>{query && <Icons.X/>}</button></label>{query && <p className="result-count">{results.length} result{results.length !== 1 && 's'} for “{query}”</p>}<div className="results">{results.map((item)=><article key={`${item.group}-${item.id}`}><span>{item.group.slice(0,-1)}</span><h2>{item.title}</h2><p>{item.excerpt || item.summary || item.description}</p><Icons.ArrowUpRight/></article>)}</div>{query && !results.length && <div className="empty">No results yet. Try a topic like “climate”, “campus” or “community”.</div>}</section>}
function App(){return <Layout><Routes><Route path="/" element={<Home/>}/><Route path="/news" element={<Listing type="news" title="News" intro="Latest news and updates from the people shaping a more sustainable XJTLU."/>}/><Route path="/blogs" element={<Listing type="blogs" title="Blogs" intro="Fresh perspectives from our students, researchers and wider community."/>}/><Route path="/activities" element={<Activities/>}/><Route path="/topics" element={<Topics/>}/><Route path="/search" element={<Search/>}/></Routes></Layout>}
export default App;
